# Configuración del sitio
title: Discord.js Bot Template
description: Una guía completa para crear bots de Discord
theme: jekyll-theme-cayman
baseurl: "/Mxrp-Template"
url: "https://syphrondev.github.io"

# Configuración de navegación
show_downloads: true
google_analytics: # Tu ID de Google Analytics (opcional)

# Configuración de markdown
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Estructura de navegación
nav_links:
  - title: Inicio
    url: /
  - title: Guía de Inicio
    url: /getting-started
  - title: Comandos
    url: /commands
  - title: Eventos
    url: /events
  - title: Base de Datos
    url: /database
  - title: Despliegue
    url: /deployment
  - title: Ejemplos
    url: /examples

# Excluir archivos
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git