title: Discord.js Bot Template
description: Una guía completa para crear bots de Discord
remote_theme: pages-themes/cayman@v0.2.0
baseurl: "/Mxrp-Template"
url: "https://syphrondev.github.io/Mxrp-Template"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-seo-tag

# Configuración de markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Estructura de navegación
navigation:
  - title: Inicio
    url: /
  - title: Guía de Inicio
    url: /getting-started.html
  - title: Comandos
    url: /commands.html
  - title: Eventos
    url: /events.html
  - title: Base de Datos
    url: /database.html
  - title: Despliegue
    url: /deployment.html
  - title: Ejemplos
    url: /examples.html

# Excluir archivos
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git