name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          
      - name: Install Dependencies
        run: |
          cd docs
          gem install bundler
          bundle install
          
      - name: Build Site
        run: |
          cd docs
          bundle exec jekyll build
          
      - name: Setup Pages
        uses: actions/configure-pages@v3
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './docs/_site'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2